# Vagrantfile for testing feeLLGood on multiple Linux distributions.

Vagrant.configure("2") do |config|

  ######################################################################
  # Common configuration.

  # Boxes vary wildly in their default amount of RAM. Set it to 4 GiB.
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  # Provision the VM by installing the feeLLGood dependencies.
  config.vm.provision "shell",
    path: "install-dependencies.sh", args: "-d", privileged: false

  # Provide read-only access to the parent directory.
  config.vm.synced_folder "..", "/home/vagrant/host-FeeLLGood",
    mount_options: ["ro"]

  ######################################################################
  # Distro-specific configuration.

  # Ubuntu development branch, future 24.04 LTS "Noble Numbat"
  config.vm.define "ubuntu_noble", autostart: false do |machine|
    machine.vm.box = "ubuntu/noble64"
  end

  # Ubuntu 22.04 LTS "Jammy Jellyfish"
  config.vm.define "ubuntu_jammy", autostart: false do |machine|
    machine.vm.box = "ubuntu/jammy64"
  end

  # Ubuntu 20.04 LTS "Focal Fossa"
  config.vm.define "ubuntu_focal", autostart: false do |machine|
    machine.vm.box = "ubuntu/focal64"
  end

  # Debian Testing, future Debian 13 "Trixie"
  config.vm.define "debian_testing", autostart: false do |machine|
    machine.vm.box = "debian/testing64"
  end

  # Debian 12 "Bookworm", released 2023-06-10
  config.vm.define "debian_bookworm", autostart: false do |machine|
    machine.vm.box = "debian/bookworm64"
  end

  # Debian 11 "Bullseye", released 2021-08-14
  config.vm.define "debian_bullseye", autostart: false do |machine|
    machine.vm.box = "debian/bullseye64"
  end

  # Rocky Linux 9, released 2022-07-14 as 9.0 "Blue Onyx"
  config.vm.define "rockylinux_9", autostart: false do |machine|
    machine.vm.box = "rockylinux/9"
    machine.vm.hostname = "rockylinux-9"
  end

end
